version: "3.8"

services:
  test_db:
    image: postgres:15.1-alpine
    container_name: test_db
    ports:
      - "5433:5433"
    command: -p 5433
    env_file:
      - test_dev.env

  test_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test_menu
    env_file:
      - test_dev.env
    ports:
      - "8080:8080"
    command: ["/menu_app/app.sh", "test"]
    depends_on:
      - test_db
